#ifndef DPRINT_CLANG_FORMAT_WASM_SYSEXITS_H
#define DPRINT_CLANG_FORMAT_WASM_SYSEXITS_H

#define EX_OK 0
#define EX_USAGE 64
#define EX_DATAERR 65
#define EX_NOINPUT 66
#define EX_SOFTWARE 70
#define EX_IOERR 74

#endif
