# Initial cache for configuring LLVM/Clang libraries as freestanding Wasm.
# This file is consumed by CMake's `-C` option when configuring LLVM itself.

get_filename_component(DPRINT_CLANG_FORMAT_REPO_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)

set(DPRINT_CLANG_FORMAT_HOST_FLAGS
    "-DLLVM_ON_UNIX -DHAVE_SYSEXITS_H=1 -DHAVE_SYSCONF=1 -DHAVE_GETRUSAGE=1 -DHAVE_SYS_MMAN_H=1 -DHAVE_DLOPEN=1")

set(DPRINT_CLANG_FORMAT_C_FLAGS
    "-ffreestanding ${DPRINT_CLANG_FORMAT_HOST_FLAGS} -DCLANG_BUILD_STATIC=1 -isystem ${DPRINT_CLANG_FORMAT_REPO_ROOT}/support/wasm-sysroot/include")
set(DPRINT_CLANG_FORMAT_CXX_FLAGS
    "-ffreestanding ${DPRINT_CLANG_FORMAT_HOST_FLAGS} -DCLANG_BUILD_STATIC=1 -fno-exceptions -fno-rtti -fno-threadsafe-statics -nostdinc++ -D_LIBCPP_DISABLE_EXTERN_TEMPLATE -isystem ${DPRINT_CLANG_FORMAT_REPO_ROOT}/support/libcxx-wasm/include -isystem ${CMAKE_SOURCE_DIR}/../libcxx/include -isystem ${CMAKE_SOURCE_DIR}/../libcxx/src/include -isystem ${DPRINT_CLANG_FORMAT_REPO_ROOT}/support/wasm-sysroot/include")

set(CMAKE_BUILD_TYPE "MinSizeRel" CACHE STRING "" FORCE)
set(CMAKE_SYSTEM_NAME "Generic" CACHE STRING "" FORCE)
set(CMAKE_C_COMPILER "clang" CACHE STRING "" FORCE)
set(CMAKE_CXX_COMPILER "clang++" CACHE STRING "" FORCE)
set(CMAKE_C_COMPILER_TARGET "wasm32-unknown-unknown" CACHE STRING "" FORCE)
set(CMAKE_CXX_COMPILER_TARGET "wasm32-unknown-unknown" CACHE STRING "" FORCE)
set(CMAKE_TRY_COMPILE_TARGET_TYPE "STATIC_LIBRARY" CACHE STRING "" FORCE)
set(CMAKE_C_FLAGS "${DPRINT_CLANG_FORMAT_C_FLAGS}" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS "${DPRINT_CLANG_FORMAT_CXX_FLAGS}" CACHE STRING "" FORCE)

set(LLVM_NATIVE_TOOL_DIR "${CMAKE_BINARY_DIR}/NATIVE/bin" CACHE PATH "" FORCE)
set(LLVM_TABLEGEN "${LLVM_NATIVE_TOOL_DIR}/llvm-tblgen" CACHE FILEPATH "" FORCE)
set(CLANG_TABLEGEN "${LLVM_NATIVE_TOOL_DIR}/clang-tblgen" CACHE FILEPATH "" FORCE)

set(LLVM_ENABLE_PROJECTS "clang" CACHE STRING "" FORCE)
set(LLVM_TARGETS_TO_BUILD "" CACHE STRING "" FORCE)
set(LLVM_INCLUDE_TESTS OFF CACHE BOOL "" FORCE)
set(LLVM_INCLUDE_BENCHMARKS OFF CACHE BOOL "" FORCE)
set(LLVM_INCLUDE_EXAMPLES OFF CACHE BOOL "" FORCE)
set(LLVM_BUILD_TOOLS OFF CACHE BOOL "" FORCE)
set(CLANG_BUILD_TOOLS OFF CACHE BOOL "" FORCE)
set(LLVM_ENABLE_BINDINGS OFF CACHE BOOL "" FORCE)
set(LLVM_ENABLE_ZLIB OFF CACHE BOOL "" FORCE)
set(LLVM_ENABLE_ZSTD OFF CACHE BOOL "" FORCE)
set(LLVM_ENABLE_LIBXML2 OFF CACHE BOOL "" FORCE)
set(LLVM_ENABLE_THREADS OFF CACHE BOOL "" FORCE)
set(LLVM_ENABLE_PIC OFF CACHE BOOL "" FORCE)
set(LLVM_ENABLE_BACKTRACES OFF CACHE BOOL "" FORCE)
set(LLVM_ENABLE_UNWIND_TABLES OFF CACHE BOOL "" FORCE)
